insert into vehicle_description([Vehicle ID],
[Vehicle Damage Extent],
[Vehicle First Impact Location],
[Vehicle Second Impact Location],
[Vehicle Body Type],
[Vehicle Movement],
[Vehicle Continuing Dir],
[Vehicle Going Dir],
[Speed Limit],
[Driverless Vehicle],
[Parked Vehicle],
[Vehicle Year],
[Vehicle Make],
[Vehicle Model],
[Equipment Problems],
[Latitude],
[Longitude],
[Location],
[Route Type],
[Road Name],
[Cross-Street Type],
[Cross-Street Name],
[Off-Road Description],
[Municipality],
[Related Non-Motorist],
[Collision Type],
[Weather],
[Surface Condition],
[Light],
[Traffic Control]) select [Vehicle ID],
[Vehicle Damage Extent],
[Vehicle First Impact Location],
[Vehicle Second Impact Location],
[Vehicle Body Type],
[Vehicle Movement],
[Vehicle Continuing Dir],
[Vehicle Going Dir],
[Speed Limit],
[Driverless Vehicle],
[Parked Vehicle],
[Vehicle Year],
[Vehicle Make],
[Vehicle Model],
[Equipment Problems],
[Latitude],
[Longitude],
[Location],
[Route Type],
[Road Name],
[Cross-Street Type],
[Cross-Street Name],
[Off-Road Description],
[Municipality],
[Related Non-Motorist],
[Collision Type],
[Weather],
[Surface Condition],
[Light],
[Traffic Control] from extract.dbo.crashReport

insert into report_description ([Report Number],
[Local Case Number],
[Agency Name],
[ACRS Report Type],
[Route Type],
[Road Name],
[Cross-Street Type],
[Cross-Street Name],
[Off-Road Description],
[Municipality],
[Related Non-Motorist],
[Collision Type],
[Weather],
[Surface Condition],
[Light],
[Traffic Control],
[Driver Substance Abuse],
[Non-Motorist Substance Abuse]) select 
[Report Number],
[Local Case Number],
[Agency Name],
[ACRS Report Type],
[Route Type],
[Road Name],
[Cross-Street Type],
[Cross-Street Name],
[Off-Road Description],
[Municipality],
[Related Non-Motorist],
[Collision Type],
[Weather],
[Surface Condition],
[Light],
[Traffic Control],
[Driver Substance Abuse],
[Non-Motorist Substance Abuse] from extract.dbo.crashReport

insert into driver_description([Person ID],[Driver At Fault],[Injury Severity],[Circumstance],[Driver Distracted By],[Drivers License State])
select [Person ID],[Driver At Fault],[Injury Severity],[Circumstance],[Driver Distracted By],[Drivers License State] from extract.dbo.crashReport

--insert into crash_fact([Report Number],[Person ID], [Vehicle ID],[Latitude] ,[Longitude],[Location])
--select [Report Number],[Person ID], [Vehicle ID],[Latitude] ,[Longitude],[Location] from extract.dbo.crashReport

